name: go-lint
on: push
jobs:
  golangci-lint:
    name: Lint golang codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2
